X(UCI,                uci)
X(DEBUG,              debug)
X(ISREADY,            isready)
X(SETOPTION,          setoption)
X(REGISTER,           register)
X(UCINEWGAME,         ucinewgame)
X(POSITION,           position)
X(GO,                 go)
X(STOP,               stop)
X(PONDERHIT,          ponderhit)
X(QUIT,               quit)

